package com.resumeshortlist.resume_shortlist_backend.service.usercv;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import com.resumeshortlist.resume_shortlist_backend.entity.usercv.AnalysisResultForUser;
import org.springframework.stereotype.Service;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;

@Service
public class UserCvPdfService {

    public ByteArrayInputStream generateOptimizedReport(AnalysisResultForUser analysis) {
        Document document = new Document();
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter.getInstance(document, out);
            document.open();

            // Styling
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 24, BaseColor.DARK_GRAY);
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, BaseColor.BLUE);
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 12, BaseColor.BLACK);

            document.add(new Paragraph("Resume Optimization Report", titleFont));
            document.add(new Paragraph("Generated by Graphura ATS Analyzer\n\n", normalFont));

            document.add(new Paragraph("Overall Score: " + analysis.getTotalScore() + "/100", headerFont));
            document.add(new Paragraph("\n"));

            document.add(new Paragraph("Matched Keywords:", headerFont));
            document.add(new Paragraph(analysis.getMatchedKeywords(), normalFont));
            document.add(new Paragraph("\n"));

            document.add(new Paragraph("Missing Keywords (To Add):", headerFont));
            document.add(new Paragraph(analysis.getMissingKeywords(), normalFont));
            document.add(new Paragraph("\n"));

            document.add(new Paragraph("AI Suggestions for Improvement:", headerFont));
            document.add(new Paragraph(analysis.getSuggestions(), normalFont));

            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        return new ByteArrayInputStream(out.toByteArray());
    }
}